// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Crd struct {
	Kind     string                 `json:"kind"`
	Group    string                 `json:"group"`
	Version  string                 `json:"version"`
	Filename string                 `json:"filename"`
	Spec     map[string]interface{} `json:"spec"`
	TagID    int64                  `json:"tagId"`
	Tag      *Tag                   `json:"tag"`
}

type Repository struct {
	Name string `json:"name"`
	Tags []*Tag `json:"tags"`
}

type Tag struct {
	ID   int64       `json:"id"`
	Name string      `json:"name"`
	Time string      `json:"time"`
	Repo *Repository `json:"repo"`
	Crds []*Crd      `json:"crds"`
}
