apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc
  namespace: crdsdev
  labels:
    app: doc
spec:
  selector:
    matchLabels:
      app: doc
  template:
    metadata:
      labels:
        app: doc
    spec:
      containers:
        - name: doc
          image: sijoma/doc:latest
          env:
            - name: ANALYTICS
              value: "false"
          ports:
            - containerPort: 5050
              name: doc
---
apiVersion: v1
kind: Service
metadata:
  name: doc
  namespace: crdsdev
  labels:
    app: doc
spec:
  ports:
    - port: 80
      targetPort: 5050
  selector:
    app: doc
  type: NodePort
