package config

import (
	"io/ioutil"

	"github.com/ghodss/yaml"
)

type DocConfig struct {
	Scan           *ScanConfig `json:"scan,omitempty"`
	TemplateFolder *string     `json:"templateFolder,omitempty"`
	ExampleProject *string     `json:"exampleProject,omitempty"`
}

type ScanConfig struct {
	Regex  *string       `json:"regex,omitempty"`
	Ignore *IgnoreConfig `json:"ignore,omitempty"`
}

type IgnoreConfig struct {
	Regex *string   `json:"regex,omitempty"`
	List  []*string `json:"list,omitempty"`
}

func LoadConfigWithDefaults(filepath string) (*DocConfig, error) {
	scanRegex := "^.*.\\.yaml"
	templateDir := "template"
	exampleProject := "github.com/crossplane/crossplane@v0.10.0"

	defaultConfig := DocConfig{
		Scan: &ScanConfig{
			Regex: &scanRegex,
		},
		TemplateFolder: &templateDir,
		ExampleProject: &exampleProject,
	}

	return LoadConfig(defaultConfig, filepath)
}

func LoadConfig(defaultConfig DocConfig, filepath string) (*DocConfig, error) {

	rawConfig, err := ioutil.ReadFile(filepath)
	if err != nil {
		return nil, err
	}

	config := defaultConfig.DeepCopy()

	err = yaml.Unmarshal(rawConfig, config)
	if err != nil {
		return nil, err
	}
	return config, nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DocConfig) DeepCopyInto(out *DocConfig) {
	*out = *in
	if in.Scan != nil {
		in, out := &in.Scan, &out.Scan
		*out = new(ScanConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TemplateFolder != nil {
		in, out := &in.TemplateFolder, &out.TemplateFolder
		*out = new(string)
		**out = **in
	}
	if in.ExampleProject != nil {
		in, out := &in.ExampleProject, &out.ExampleProject
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchConfig.
func (in *DocConfig) DeepCopy() *DocConfig {
	if in == nil {
		return nil
	}
	out := new(DocConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanConfig) DeepCopyInto(out *ScanConfig) {
	*out = *in
	if in.Regex != nil {
		in, out := &in.Regex, &out.Regex
		*out = new(string)
		**out = **in
	}
	if in.Ignore != nil {
		in, out := &in.Ignore, &out.Ignore
		*out = new(IgnoreConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchConfig.
func (in *ScanConfig) DeepCopy() *ScanConfig {
	if in == nil {
		return nil
	}
	out := new(ScanConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *IgnoreConfig) DeepCopyInto(out *IgnoreConfig) {
	*out = *in
	if in.Regex != nil {
		in, out := &in.Regex, &out.Regex
		*out = new(string)
		**out = **in
	}

	if in.List != nil {
		in, out := &in.List, &out.List
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

func (in *IgnoreConfig) DeepCopy() *IgnoreConfig {
	if in == nil {
		return nil
	}
	out := new(IgnoreConfig)
	in.DeepCopyInto(out)
	return out
}
